// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxjvzmcvpsnfqtglumjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4anZ6bWN2cHNuZnF0Z2x1bWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTk2MzYsImV4cCI6MjA2MDA5NTYzNn0.gn7301A8nXjLYNUpmBmiRqGeRL1MfFc_t7m63t-gXEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);